### ISSUE TITLE
Unable to install, perhaps broken Provider reference

### ISSUE THREAD

**Issue by tonybrasunas** [yairhaimo/angular-feature-toggle#3]
Get this error after npm install and adding appropriate lines of code to app.js. 

`Error: [$injector:modulerr] Failed to instantiate module icarusApp due to:
[$injector:modulerr] Failed to instantiate module yh.featureToggle due to:
[$injector:unpr] Unknown provider: featureToggleProvider`

**Comment by yairhaimo** [comment]
Can you please paste your code that uses the plugin? It will help with debugging the problem.

**Comment by tonybrasunas** [comment]
Just using the code from the example:

App.js:
`angular.module('angularApp', [
  'gettext',
  'hyperRest',
  ...
  'yh.featureToggle',
  ...
  'xml'
])`

The script was loaded in index.html, and I could view source on the page and find your script. So the script was definitely present.

The error shows a bad reference to the Provider, perhaps? 
I tried pasting your code at the top of app.js, to see if that would work. Then I even tried editing your code, renaming featureToggleProvider to 'featureToggle' in the spots where it appears it should be directly referencing the provider by name. But no luck with that either.  Feels like there's a bug in your code, but not sure. 

Seems like a great module, if it works.

**Comment by yairhaimo** [comment]
Is it possible that one of the earlier module prerequisite use the feature toggle? (either gettext or hyperRest or any other that comes before the yh.featureToggle).
You can either move the "yh.featureToggle" to the beginning of the prerequisite array (before gettext) or add "yh.featureToggle" as a prerequisite in the inner modules that use it.

You can check the plunker example to see that i added "yh.featureToggle" as a prerequisite for both the "app" module and the "app.components" modules.

Let me know if it helped and sorry if it didnt :/

**Comment by tonybrasunas** [comment]
Didn't help. Using another module. All good.

**Comment by yairhaimo** [comment]
Ok, sorry for that.
