### ISSUE TITLE
Support Bower installation

### ISSUE THREAD

**Issue by haysclark** [yairhaimo/angular-feature-toggle#4]
Seems like this should be a 'bower' plug-in, not a NPM plug-in as Angular is client side JS.

How to create Bower package:
http://bower.io/docs/creating-packages/

Example project that supports both NPM and Bower installation:
https://www.npmjs.com/package/angular-mocks

**Comment by haysclark** [comment]
Copying this issue to Mixpo/angular-feature-toggle

**Comment by yairhaimo** [comment]
added bower installation support
