### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by willsteinmetz** [yairhaimo/angular-feature-toggle#8]
My organization is evaluating packages with this functionality for use in our projects. However, we have a mandate to only use packages that are still maintained. Is this package still being actively maintained?

**Comment by yairhaimo** [comment]
Hi Will,
I am not actively maintaining this package and honestly I would have done it different if I were to implement it today.
You're free to use it/fork it and I'll help with whatever questions you might have.

**Comment by willsteinmetz** [comment]
Thanks for the update!
